### ISSUE TITLE
Special treatment for empty jars

### ISSUE THREAD

**Issue by obriencj** [project-ncl/build-finder#784]
There are a few bad situations where an empty JAR ends up in koji -- multiple builds will have an artifact with that matching empty-zip checksum, `76cdb2bad9582d23c1f6f4d868218d6c`

In those cases it is probably better to completely ignore that JAR rather than trying to map it to any build at all.

However an alternative may be to alter how it is handled when a query for an archive checksum returns multiple matches -- at that point require that the filename also matches. If it does not, then consider there to be no match found.

**Comment by obriencj** [comment]
jumping in cold to the sources here, I think I'm seeing that it will attempt to find a match in PNC first, with preference being first-found of a sorted set of builds based on their "quality" level. So I'm not entirely sure that there truly are duplicates of the empty zip/jar inside PNC itself. There may only be one PNC build that ever produced that before -- in that case a special check just for the empty case might be most appropriate.

**Comment by dwalluck** [comment]
There's already a check that skips the checksum of an empty file. Maybe we can just add empty zip file to that check.

If multiple builds are returned by Brew or PNC, it is always mapped to just a single build using some algorithm. For Brew, it tries to determine the "best" build of the set.

**Comment by michalovjan** [comment]
We've hit this issue when creating nvr list. It identified a koji nvr that produced an empty zip. This nvr had security issues which was problematic.
